version: "3.8"

services:
  api:
    build: ./api
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: dein_benutzername
      DB_PASSWORD: dein_passwort
      DB_DATABASE: deine_datenbank

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: dein_benutzername
      POSTGRES_PASSWORD: dein_passwort
      POSTGRES_DB: deine_datenbank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
